AllCops:
  EnabledByDefault: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30

Metrics/LineLength:
  Max: 120
  Exclude:
    - lib/tasks/cucumber.rake

Rails/FilePath:
  Exclude:
    - lib/tasks/cucumber.rake

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update
