language: ruby
rvm:
 - 2.5.4

services:
  - postgresql

script:
  - bin/setup
  - bundle exec cucumber
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email:
    on_success: never
    on_failure: never
