language: ruby
rvm:
 - 2.5.4

rubocop:
  script:
    - bundle exec rubocop

cucumber:
  services:
    - postgresql
  script:
  - bin/setup
  - bundle exec cucumber

notifications:
  email:
    on_success: never
    on_failure: never
